package ba.unsa.etf.si.tim8.mlmarketing.models;

// default package
// Generated May 9, 2016 2:18:54 AM by Hibernate Tools 5.0.0.Alpha3

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Akterprodaje generated by hbm2java
 */
@Entity
@Table(name = "akterprodaje", catalog = "tim8")
public class Akterprodaje implements java.io.Serializable {

	private Integer id;
	private Akterprodaje akterprodaje;
	private Regija regija;
	private String tip;
	private String ime;
	private String prezime;
	private String adresa;
	private String email;
	private String brojtelefona;
	private Set<Faktura> fakturas = new HashSet<Faktura>(0);
	private Set<Akterprodaje> akterprodajes = new HashSet<Akterprodaje>(0);
	private Set<Narudzba> narudzbas = new HashSet<Narudzba>(0);

	public Akterprodaje() {
	}

	public Akterprodaje(Regija regija, String tip, String ime, String prezime, String adresa, String email,
			String brojtelefona) {
		this.regija = regija;
		this.tip = tip;
		this.ime = ime;
		this.prezime = prezime;
		this.adresa = adresa;
		this.email = email;
		this.brojtelefona = brojtelefona;
	}

	public Akterprodaje(Akterprodaje akterprodaje, Regija regija, String tip, String ime, String prezime, String adresa,
			String email, String brojtelefona, Set<Faktura> fakturas, Set<Akterprodaje> akterprodajes,
			Set<Narudzba> narudzbas) {
		this.akterprodaje = akterprodaje;
		this.regija = regija;
		this.tip = tip;
		this.ime = ime;
		this.prezime = prezime;
		this.adresa = adresa;
		this.email = email;
		this.brojtelefona = brojtelefona;
		this.fakturas = fakturas;
		this.akterprodajes = akterprodajes;
		this.narudzbas = narudzbas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "odgovornimenadzer")
	public Akterprodaje getAkterprodaje() {
		return this.akterprodaje;
	}

	public void setAkterprodaje(Akterprodaje akterprodaje) {
		this.akterprodaje = akterprodaje;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "regijaid", nullable = false)
	public Regija getRegija() {
		return this.regija;
	}

	public void setRegija(Regija regija) {
		this.regija = regija;
	}

	@Column(name = "tip", nullable = false, length = 45)
	public String getTip() {
		return this.tip;
	}

	public void setTip(String tip) {
		this.tip = tip;
	}

	@Column(name = "ime", nullable = false, length = 45)
	public String getIme() {
		return this.ime;
	}

	public void setIme(String ime) {
		this.ime = ime;
	}

	@Column(name = "prezime", nullable = false, length = 45)
	public String getPrezime() {
		return this.prezime;
	}

	public void setPrezime(String prezime) {
		this.prezime = prezime;
	}

	@Column(name = "adresa", nullable = false, length = 45)
	public String getAdresa() {
		return this.adresa;
	}

	public void setAdresa(String adresa) {
		this.adresa = adresa;
	}

	@Column(name = "email", nullable = false, length = 90)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "brojtelefona", nullable = false, length = 45)
	public String getBrojtelefona() {
		return this.brojtelefona;
	}

	public void setBrojtelefona(String brojtelefona) {
		this.brojtelefona = brojtelefona;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "akterprodaje")
	public Set<Faktura> getFakturas() {
		return this.fakturas;
	}

	public void setFakturas(Set<Faktura> fakturas) {
		this.fakturas = fakturas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "akterprodaje")
	public Set<Akterprodaje> getAkterprodajes() {
		return this.akterprodajes;
	}

	public void setAkterprodajes(Set<Akterprodaje> akterprodajes) {
		this.akterprodajes = akterprodajes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "akterprodaje")
	public Set<Narudzba> getNarudzbas() {
		return this.narudzbas;
	}

	public void setNarudzbas(Set<Narudzba> narudzbas) {
		this.narudzbas = narudzbas;
	}

}
