package ba.unsa.etf.si.tim8.mlmarketing.models;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated May 13, 2016 11:55:21 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Faktura generated by hbm2java
 */
@Entity
@Table(name = "faktura", catalog = "tim8")
public class Faktura implements java.io.Serializable {

	private Integer id;
	private Akterprodaje akterprodaje;
	private Regija regija;
	private double ukupnacijena;
	private Date datum;
	private String imeaktera;
	private String imeregije;
	private Set<ProizvodFaktura> proizvodFakturas = new HashSet<ProizvodFaktura>(0);

	public Faktura() {
	}

	public Faktura(double ukupnacijena, Date datum, String imeaktera, String imeregije) {
		this.ukupnacijena = ukupnacijena;
		this.datum = datum;
		this.imeaktera = imeaktera;
		this.imeregije = imeregije;
	}

	public Faktura(Akterprodaje akterprodaje, Regija regija, double ukupnacijena, Date datum, String imeaktera,
			String imeregije, Set<ProizvodFaktura> proizvodFakturas) {
		this.akterprodaje = akterprodaje;
		this.regija = regija;
		this.ukupnacijena = ukupnacijena;
		this.datum = datum;
		this.imeaktera = imeaktera;
		this.imeregije = imeregije;
		this.proizvodFakturas = proizvodFakturas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "akterid")
	public Akterprodaje getAkterprodaje() {
		return this.akterprodaje;
	}

	public void setAkterprodaje(Akterprodaje akterprodaje) {
		this.akterprodaje = akterprodaje;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "regijaid")
	public Regija getRegija() {
		return this.regija;
	}

	public void setRegija(Regija regija) {
		this.regija = regija;
	}

	@Column(name = "ukupnacijena", nullable = false, precision = 22, scale = 0)
	public double getUkupnacijena() {
		return this.ukupnacijena;
	}

	public void setUkupnacijena(double ukupnacijena) {
		this.ukupnacijena = ukupnacijena;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datum", nullable = false, length = 19)
	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	@Column(name = "imeaktera", nullable = false, length = 91)
	public String getImeaktera() {
		return this.imeaktera;
	}

	public void setImeaktera(String imeaktera) {
		this.imeaktera = imeaktera;
	}

	@Column(name = "imeregije", nullable = false, length = 90)
	public String getImeregije() {
		return this.imeregije;
	}

	public void setImeregije(String imeregije) {
		this.imeregije = imeregije;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "faktura")
	public Set<ProizvodFaktura> getProizvodFakturas() {
		return this.proizvodFakturas;
	}

	public void setProizvodFakturas(Set<ProizvodFaktura> proizvodFakturas) {
		this.proizvodFakturas = proizvodFakturas;
	}

}
