package ba.unsa.etf.si.tim8.mlmarketing.models;
// Generated May 8, 2016 6:21:50 PM by Hibernate Tools 5.0.0.Alpha3

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Faktura generated by hbm2java
 */
@Entity
@Table(name = "faktura", catalog = "tim8")
public class Faktura implements java.io.Serializable {

	private Integer id;
	private Akterprodaje akterprodaje;
	private String ukupnacijena;
	private String datum;
	private Set<ProizvodFaktura> proizvodFakturas = new HashSet<ProizvodFaktura>(0);

	public Faktura() {
	}

	public Faktura(Akterprodaje akterprodaje, String ukupnacijena, String datum) {
		this.akterprodaje = akterprodaje;
		this.ukupnacijena = ukupnacijena;
		this.datum = datum;
	}

	public Faktura(Akterprodaje akterprodaje, String ukupnacijena, String datum,
			Set<ProizvodFaktura> proizvodFakturas) {
		this.akterprodaje = akterprodaje;
		this.ukupnacijena = ukupnacijena;
		this.datum = datum;
		this.proizvodFakturas = proizvodFakturas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "akterid", nullable = false)
	public Akterprodaje getAkterprodaje() {
		return this.akterprodaje;
	}

	public void setAkterprodaje(Akterprodaje akterprodaje) {
		this.akterprodaje = akterprodaje;
	}

	@Column(name = "ukupnacijena", nullable = false, length = 45)
	public String getUkupnacijena() {
		return this.ukupnacijena;
	}

	public void setUkupnacijena(String ukupnacijena) {
		this.ukupnacijena = ukupnacijena;
	}

	@Column(name = "datum", nullable = false, length = 45)
	public String getDatum() {
		return this.datum;
	}

	public void setDatum(String datum) {
		this.datum = datum;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "faktura")
	public Set<ProizvodFaktura> getProizvodFakturas() {
		return this.proizvodFakturas;
	}

	public void setProizvodFakturas(Set<ProizvodFaktura> proizvodFakturas) {
		this.proizvodFakturas = proizvodFakturas;
	}

}
