package ba.unsa.etf.si.tim8.mlmarketing.models;

// default package
// Generated May 9, 2016 2:18:54 AM by Hibernate Tools 5.0.0.Alpha3

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Faktura generated by hbm2java
 */
@Entity
@Table(name = "faktura", catalog = "tim8")
public class Faktura implements java.io.Serializable {

	private Integer id;
	private Akterprodaje akterprodaje;
	private double ukupnacijena;
	private Date datum;
	private Set<ProizvodFaktura> proizvodFakturas = new HashSet<ProizvodFaktura>(0);

	public Faktura() {
	}

	public Faktura(Akterprodaje akterprodaje, double ukupnacijena, Date datum) {
		this.akterprodaje = akterprodaje;
		this.ukupnacijena = ukupnacijena;
		this.datum = datum;
	}

	public Faktura(Akterprodaje akterprodaje, double ukupnacijena, Date datum, Set<ProizvodFaktura> proizvodFakturas) {
		this.akterprodaje = akterprodaje;
		this.ukupnacijena = ukupnacijena;
		this.datum = datum;
		this.proizvodFakturas = proizvodFakturas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "akterid", nullable = false)
	public Akterprodaje getAkterprodaje() {
		return this.akterprodaje;
	}

	public void setAkterprodaje(Akterprodaje akterprodaje) {
		this.akterprodaje = akterprodaje;
	}

	@Column(name = "ukupnacijena", nullable = false, precision = 22, scale = 0)
	public double getUkupnacijena() {
		return this.ukupnacijena;
	}

	public void setUkupnacijena(double ukupnacijena) {
		this.ukupnacijena = ukupnacijena;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datum", nullable = false, length = 19)
	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "faktura")
	public Set<ProizvodFaktura> getProizvodFakturas() {
		return this.proizvodFakturas;
	}

	public void setProizvodFakturas(Set<ProizvodFaktura> proizvodFakturas) {
		this.proizvodFakturas = proizvodFakturas;
	}

}
