package ba.unsa.etf.si.tim8.mlmarketing.models;
// Generated May 8, 2016 6:21:50 PM by Hibernate Tools 5.0.0.Alpha3

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProizvodFaktura generated by hbm2java
 */
@Entity
@Table(name = "proizvod_faktura", catalog = "tim8")
public class ProizvodFaktura implements java.io.Serializable {

	private Integer id;
	private Faktura faktura;
	private Proizvod proizvod;
	private int kolicina;
	private double cijena;

	public ProizvodFaktura() {
	}

	public ProizvodFaktura(Faktura faktura, Proizvod proizvod, int kolicina, double cijena) {
		this.faktura = faktura;
		this.proizvod = proizvod;
		this.kolicina = kolicina;
		this.cijena = cijena;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fakturaid", nullable = false)
	public Faktura getFaktura() {
		return this.faktura;
	}

	public void setFaktura(Faktura faktura) {
		this.faktura = faktura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proizvodid", nullable = false)
	public Proizvod getProizvod() {
		return this.proizvod;
	}

	public void setProizvod(Proizvod proizvod) {
		this.proizvod = proizvod;
	}

	@Column(name = "kolicina", nullable = false)
	public int getKolicina() {
		return this.kolicina;
	}

	public void setKolicina(int kolicina) {
		this.kolicina = kolicina;
	}

	@Column(name = "cijena", nullable = false, precision = 22, scale = 0)
	public double getCijena() {
		return this.cijena;
	}

	public void setCijena(double cijena) {
		this.cijena = cijena;
	}

}
