package ba.unsa.etf.si.tim8.mlmarketing.models;

// default package
// Generated May 13, 2016 11:55:21 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProizvodFaktura generated by hbm2java
 */
@Entity
@Table(name = "proizvod_faktura", catalog = "tim8")
public class ProizvodFaktura implements java.io.Serializable {

	private Integer id;
	private Faktura faktura;
	private Proizvod proizvod;
	private String nazivproizvoda;
	private double prodajnacijena;
	private double nabavnacijena;
	private int kolicina;

	public ProizvodFaktura() {
	}

	public ProizvodFaktura(Faktura faktura, String nazivproizvoda, double prodajnacijena, double nabavnacijena,
			int kolicina) {
		this.faktura = faktura;
		this.nazivproizvoda = nazivproizvoda;
		this.prodajnacijena = prodajnacijena;
		this.nabavnacijena = nabavnacijena;
		this.kolicina = kolicina;
	}

	public ProizvodFaktura(Faktura faktura, Proizvod proizvod, String nazivproizvoda, double prodajnacijena,
			double nabavnacijena, int kolicina) {
		this.faktura = faktura;
		this.proizvod = proizvod;
		this.nazivproizvoda = nazivproizvoda;
		this.prodajnacijena = prodajnacijena;
		this.nabavnacijena = nabavnacijena;
		this.kolicina = kolicina;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fakturaid", nullable = false)
	public Faktura getFaktura() {
		return this.faktura;
	}

	public void setFaktura(Faktura faktura) {
		this.faktura = faktura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proizvodid")
	public Proizvod getProizvod() {
		return this.proizvod;
	}

	public void setProizvod(Proizvod proizvod) {
		this.proizvod = proizvod;
	}

	@Column(name = "nazivproizvoda", nullable = false, length = 90)
	public String getNazivproizvoda() {
		return this.nazivproizvoda;
	}

	public void setNazivproizvoda(String nazivproizvoda) {
		this.nazivproizvoda = nazivproizvoda;
	}

	@Column(name = "prodajnacijena", nullable = false, precision = 22, scale = 0)
	public double getProdajnacijena() {
		return this.prodajnacijena;
	}

	public void setProdajnacijena(double prodajnacijena) {
		this.prodajnacijena = prodajnacijena;
	}

	@Column(name = "nabavnacijena", nullable = false, precision = 22, scale = 0)
	public double getNabavnacijena() {
		return this.nabavnacijena;
	}

	public void setNabavnacijena(double nabavnacijena) {
		this.nabavnacijena = nabavnacijena;
	}

	@Column(name = "kolicina", nullable = false)
	public int getKolicina() {
		return this.kolicina;
	}

	public void setKolicina(int kolicina) {
		this.kolicina = kolicina;
	}

}
