package ba.unsa.etf.si.tim8.mlmarketing.models;
// Generated May 8, 2016 6:21:50 PM by Hibernate Tools 5.0.0.Alpha3

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProizvodNarudzba generated by hbm2java
 */
@Entity
@Table(name = "proizvod_narudzba", catalog = "tim8")
public class ProizvodNarudzba implements java.io.Serializable {

	private Integer id;
	private Narudzba narudzba;
	private Proizvod proizvod;
	private String kolicina;

	public ProizvodNarudzba() {
	}

	public ProizvodNarudzba(Narudzba narudzba, Proizvod proizvod, String kolicina) {
		this.narudzba = narudzba;
		this.proizvod = proizvod;
		this.kolicina = kolicina;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "narudzbaid", nullable = false)
	public Narudzba getNarudzba() {
		return this.narudzba;
	}

	public void setNarudzba(Narudzba narudzba) {
		this.narudzba = narudzba;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proizvodid", nullable = false)
	public Proizvod getProizvod() {
		return this.proizvod;
	}

	public void setProizvod(Proizvod proizvod) {
		this.proizvod = proizvod;
	}

	@Column(name = "kolicina", nullable = false, length = 45)
	public String getKolicina() {
		return this.kolicina;
	}

	public void setKolicina(String kolicina) {
		this.kolicina = kolicina;
	}

}
